name: Build and Deploy Github Pages
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Setup Node.js & Cache Dependencies ⚡️
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          export PIC_DEPLOY_DIR='/VNSTAT-DASHBOARD'
          npm install
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: dist/spa # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
